import type { Meal } from '@/types/meals';

/**
 * Seed database of Filipino meals.
 * Ingredient quantities use kg for produce/meat (matching Blumentritt Market API
 * prices at PHP/kg) and piece/pack/bottle/block for discrete items.
 *
 * Real Blumentritt Market prices (as of 2026-03-31):
 *   Rice 55/kg · Pork Belly 420/kg · Pork Kasim 320/kg · Chicken ~200/kg
 *   Garlic 120/kg · Ginger 160/kg · Onion 120/kg · Tomato 60/kg
 *   Sitao 120/kg · Sayote 60/kg · Squash 100/kg · Eggplant 100/kg
 *   Calamansi 140/kg · Cooking Oil 85/L · Brown Sugar 65/kg
 */
export const FILIPINO_MEALS: Meal[] = [
  // ─── BREAKFAST ────────────────────────────────────────────────
  {
    id: 'arroz-caldo',
    name: 'Arroz Caldo',
    nameTagalog: 'Arroz Caldo',
    category: 'breakfast',
    ingredients: [
      { id: 'rice', name: 'Rice', unit: 'kg', quantity: 0.2 },
      { id: 'chicken', name: 'Chicken', unit: 'kg', quantity: 0.25 },
      { id: 'ginger', name: 'Ginger', unit: 'kg', quantity: 0.03 },
      { id: 'bawang', name: 'Garlic', nameTagalog: 'Bawang', unit: 'kg', quantity: 0.02 },
      { id: 'sibuyas', name: 'Onion', nameTagalog: 'Sibuyas', unit: 'kg', quantity: 0.05 },
      { id: 'cooking-oil', name: 'Cooking Oil', unit: 'L', quantity: 0.03 },
    ],
    recipe: '1. Sauté garlic, onion, and ginger in oil until fragrant.\n2. Add chicken pieces and cook until lightly browned.\n3. Pour in 4 cups of water and bring to a boil.\n4. Add rice, stir well, and reduce heat to medium-low.\n5. Simmer for 20 minutes, stirring occasionally to prevent sticking.\n6. Season with patis (fish sauce) and pepper.\n7. Serve topped with fried garlic, chopped scallions, and calamansi on the side.',
    calories: 280,
    tags: ['light', 'calming', 'warm'],
    prepMinutes: 25,
  },
  {
    id: 'lugaw',
    name: 'Lugaw',
    nameTagalog: 'Lugaw',
    category: 'breakfast',
    ingredients: [
      { id: 'rice', name: 'Rice', unit: 'kg', quantity: 0.2 },
      { id: 'ginger', name: 'Ginger', unit: 'kg', quantity: 0.03 },
      { id: 'bawang', name: 'Garlic', nameTagalog: 'Bawang', unit: 'kg', quantity: 0.02 },
    ],
    recipe: '1. Rinse rice and place in a pot with 6 cups of water.\n2. Add sliced ginger and bring to a boil.\n3. Reduce heat and simmer for 20 minutes, stirring frequently until thick and porridge-like.\n4. Season with salt and pepper.\n5. Serve with fried garlic on top and a side of patis.',
    calories: 180,
    tags: ['light', 'calming', 'low-cost'],
    prepMinutes: 20,
  },
  {
    id: 'longsilog',
    name: 'Longsilog',
    nameTagalog: 'Longsilog',
    category: 'breakfast',
    ingredients: [
      { id: 'longganisa', name: 'Longganisa', unit: 'pack', quantity: 1 },
      { id: 'rice', name: 'Sinangag (Garlic Fried Rice)', unit: 'kg', quantity: 0.3 },
      { id: 'egg', name: 'Egg', unit: 'piece', quantity: 2 },
      { id: 'bawang', name: 'Garlic', nameTagalog: 'Bawang', unit: 'kg', quantity: 0.02 },
      { id: 'cooking-oil', name: 'Cooking Oil', unit: 'L', quantity: 0.05 },
    ],
    recipe: '1. Cook longganisa: place in a pan with a little water, cover, and simmer until water evaporates. Let the sausages fry in their own oil until browned.\n2. Fry eggs sunny-side up in a separate pan.\n3. Make sinangag: sauté minced garlic in oil until golden, add day-old rice, and toss until heated through. Season with salt.\n4. Plate the garlic rice, longganisa, and fried eggs together.\n5. Serve with vinegar dipping sauce (sukang may sili).',
    calories: 520,
    tags: ['savory', 'filling', 'high-protein'],
    prepMinutes: 15,
  },
  {
    id: 'tapsilog',
    name: 'Tapsilog',
    nameTagalog: 'Tapsilog',
    category: 'breakfast',
    ingredients: [
      { id: 'pork-belly', name: 'Beef Tapa (or Pork)', unit: 'kg', quantity: 0.25 },
      { id: 'rice', name: 'Sinangag (Garlic Fried Rice)', unit: 'kg', quantity: 0.3 },
      { id: 'egg', name: 'Egg', unit: 'piece', quantity: 2 },
      { id: 'bawang', name: 'Garlic', nameTagalog: 'Bawang', unit: 'kg', quantity: 0.03 },
      { id: 'toyo', name: 'Soy Sauce', unit: 'bottle', quantity: 0.1 },
      { id: 'cooking-oil', name: 'Cooking Oil', unit: 'L', quantity: 0.05 },
    ],
    recipe: '1. Marinate thinly sliced meat in soy sauce, calamansi juice, garlic, sugar, and pepper for at least 1 hour (or overnight).\n2. Pan-fry the tapa in oil over medium-high heat until caramelized and cooked through, about 3–4 minutes per side.\n3. Fry eggs sunny-side up.\n4. Make sinangag: sauté minced garlic in oil until golden, add day-old rice, and toss.\n5. Serve together with vinegar dipping sauce.',
    calories: 560,
    tags: ['savory', 'filling', 'high-protein'],
    prepMinutes: 20,
  },
  {
    id: 'champorado',
    name: 'Champorado',
    nameTagalog: 'Champorado',
    category: 'breakfast',
    ingredients: [
      { id: 'rice', name: 'Glutinous Rice (Malagkit)', unit: 'kg', quantity: 0.2 },
      { id: 'sugar', name: 'Brown Sugar', unit: 'kg', quantity: 0.05 },
    ],
    recipe: '1. Rinse glutinous rice and place in a pot with 4 cups of water.\n2. Bring to a boil and cook until rice is soft and thick, about 15 minutes.\n3. Add tablea (or cocoa powder) and sugar, stirring until fully dissolved.\n4. Simmer for another 5 minutes until thick and chocolatey.\n5. Serve warm with evaporated milk drizzled on top.\n6. Optional: pair with tuyo (dried fish) for a sweet-salty combo.',
    calories: 320,
    tags: ['light', 'calming', 'warm', 'low-cost'],
    prepMinutes: 25,
  },
  {
    id: 'tortang-talong',
    name: 'Tortang Talong',
    nameTagalog: 'Tortang Talong',
    category: 'breakfast',
    ingredients: [
      { id: 'talong', name: 'Eggplant', nameTagalog: 'Talong', unit: 'kg', quantity: 0.3 },
      { id: 'egg', name: 'Egg', unit: 'piece', quantity: 3 },
      { id: 'sibuyas', name: 'Onion', nameTagalog: 'Sibuyas', unit: 'kg', quantity: 0.05 },
      { id: 'kamatis', name: 'Tomato', nameTagalog: 'Kamatis', unit: 'kg', quantity: 0.05 },
      { id: 'cooking-oil', name: 'Cooking Oil', unit: 'L', quantity: 0.1 },
    ],
    recipe: '1. Grill or char eggplants over an open flame (or under a broiler) until the skin is blackened and flesh is soft.\n2. Peel off the charred skin and flatten each eggplant with a fork.\n3. Beat eggs in a bowl, season with salt and pepper.\n4. Dip each flattened eggplant into the beaten egg.\n5. Pan-fry in oil over medium heat until golden brown on both sides, about 2–3 minutes per side.\n6. Serve with rice and banana ketchup or vinegar.',
    calories: 250,
    tags: ['light', 'savory', 'low-cost'],
    prepMinutes: 20,
  },

  // ─── LUNCH ────────────────────────────────────────────────────
  {
    id: 'sinigang-baboy',
    name: 'Sinigang na Baboy',
    nameTagalog: 'Sinigang na Baboy',
    category: 'lunch',
    ingredients: [
      { id: 'pork-belly', name: 'Pork Belly', unit: 'kg', quantity: 0.5 },
      { id: 'kangkong', name: 'Kangkong', unit: 'kg', quantity: 0.15 },
      { id: 'sampalok', name: 'Sampalok Mix', unit: 'pack', quantity: 1 },
      { id: 'sitaw', name: 'Sitaw (String Beans)', unit: 'kg', quantity: 0.1 },
      { id: 'kamatis', name: 'Tomato', nameTagalog: 'Kamatis', unit: 'kg', quantity: 0.1 },
      { id: 'sibuyas', name: 'Onion', nameTagalog: 'Sibuyas', unit: 'kg', quantity: 0.05 },
    ],
    recipe: '1. Boil pork belly in a pot with quartered tomatoes and sliced onion for 30 minutes until tender.\n2. Skim off any scum that rises to the surface.\n3. Add the sampalok mix (or fresh tamarind) and stir to dissolve.\n4. Add sliced radish and string beans; cook for 5 minutes.\n5. Add kangkong and green chili. Cook for 2 more minutes.\n6. Season with patis (fish sauce) to taste.\n7. Serve hot over steamed rice.',
    calories: 420,
    tags: ['savory', 'filling'],
    prepMinutes: 40,
  },
  {
    id: 'adobong-manok',
    name: 'Adobong Manok',
    nameTagalog: 'Adobong Manok',
    category: 'lunch',
    ingredients: [
      { id: 'chicken', name: 'Chicken', unit: 'kg', quantity: 0.5 },
      { id: 'toyo', name: 'Soy Sauce', unit: 'bottle', quantity: 0.15 },
      { id: 'suka', name: 'Vinegar', unit: 'bottle', quantity: 0.1 },
      { id: 'bawang', name: 'Garlic', nameTagalog: 'Bawang', unit: 'kg', quantity: 0.03 },
      { id: 'cooking-oil', name: 'Cooking Oil', unit: 'L', quantity: 0.03 },
    ],
    recipe: '1. Combine chicken, soy sauce, vinegar, crushed garlic, bay leaves, and whole peppercorns in a pot.\n2. Marinate for 15 minutes (or longer for deeper flavor).\n3. Bring to a boil, then reduce heat and simmer covered for 25 minutes until chicken is cooked.\n4. Remove chicken pieces and pan-fry in oil until skin is crispy.\n5. Reduce the sauce in the pot until slightly thickened.\n6. Return chicken to the pot and toss in the sauce.\n7. Serve over hot steamed rice.',
    calories: 380,
    tags: ['savory', 'filling', 'high-protein'],
    prepMinutes: 35,
  },
  {
    id: 'bistek-tagalog',
    name: 'Bistek Tagalog',
    nameTagalog: 'Bistek Tagalog',
    category: 'lunch',
    ingredients: [
      { id: 'pork-belly', name: 'Beef Sirloin (or Pork)', unit: 'kg', quantity: 0.3 },
      { id: 'toyo', name: 'Soy Sauce', unit: 'bottle', quantity: 0.1 },
      { id: 'calamansi', name: 'Calamansi', unit: 'kg', quantity: 0.05 },
      { id: 'sibuyas', name: 'Onion', nameTagalog: 'Sibuyas', unit: 'kg', quantity: 0.15 },
      { id: 'cooking-oil', name: 'Cooking Oil', unit: 'L', quantity: 0.03 },
    ],
    recipe: '1. Marinate thinly sliced beef in soy sauce and calamansi juice for 30 minutes.\n2. Heat oil in a pan over high heat. Sear the beef slices quickly, about 1 minute per side. Set aside.\n3. In the same pan, sauté onion rings until softened and slightly caramelized.\n4. Return beef to the pan and pour in the remaining marinade.\n5. Simmer for 5 minutes until sauce reduces.\n6. Season with pepper to taste.\n7. Serve over steamed rice topped with the caramelized onions.',
    calories: 400,
    tags: ['savory', 'filling', 'high-protein'],
    prepMinutes: 35,
  },
  {
    id: 'ginisang-sitaw',
    name: 'Ginisang Sitaw',
    nameTagalog: 'Ginisang Sitaw',
    category: 'lunch',
    ingredients: [
      { id: 'sitaw', name: 'Sitaw (String Beans)', unit: 'kg', quantity: 0.3 },
      { id: 'pork-ground', name: 'Ground Pork', unit: 'kg', quantity: 0.2 },
      { id: 'bawang', name: 'Garlic', nameTagalog: 'Bawang', unit: 'kg', quantity: 0.02 },
      { id: 'sibuyas', name: 'Onion', nameTagalog: 'Sibuyas', unit: 'kg', quantity: 0.05 },
      { id: 'kamatis', name: 'Tomato', nameTagalog: 'Kamatis', unit: 'kg', quantity: 0.1 },
      { id: 'cooking-oil', name: 'Cooking Oil', unit: 'L', quantity: 0.03 },
    ],
    recipe: '1. Sauté garlic and onion in oil until fragrant.\n2. Add ground pork and cook until browned, breaking it apart.\n3. Add diced tomatoes and cook until softened.\n4. Add sitaw cut into 2-inch pieces. Stir-fry for 3 minutes.\n5. Add a splash of water, cover, and simmer for 5 minutes until beans are tender-crisp.\n6. Season with patis and pepper.\n7. Serve with steamed rice.',
    calories: 340,
    tags: ['savory', 'light'],
    prepMinutes: 20,
  },

  // ─── DINNER ───────────────────────────────────────────────────
  {
    id: 'tinolang-manok',
    name: 'Tinolang Manok',
    nameTagalog: 'Tinolang Manok',
    category: 'dinner',
    ingredients: [
      { id: 'chicken', name: 'Chicken', unit: 'kg', quantity: 0.5 },
      { id: 'sayote', name: 'Sayote', unit: 'kg', quantity: 0.25 },
      { id: 'malunggay', name: 'Malunggay Leaves', unit: 'kg', quantity: 0.05 },
      { id: 'ginger', name: 'Ginger', unit: 'kg', quantity: 0.03 },
      { id: 'sibuyas', name: 'Onion', nameTagalog: 'Sibuyas', unit: 'kg', quantity: 0.05 },
    ],
    recipe: '1. Sauté ginger and onion in a pot until fragrant.\n2. Add chicken pieces and cook until lightly seared.\n3. Pour in 5 cups of water and bring to a boil.\n4. Reduce heat and simmer for 20 minutes until chicken is tender.\n5. Add wedged sayote and cook for 5 minutes.\n6. Add malunggay leaves and cook for 1 minute more.\n7. Season with patis and pepper. Serve with steamed rice.',
    calories: 310,
    tags: ['calming', 'light', 'high-protein'],
    prepMinutes: 35,
  },
  {
    id: 'paksiw-bangus',
    name: 'Paksiw na Bangus',
    nameTagalog: 'Paksiw na Bangus',
    category: 'dinner',
    ingredients: [
      { id: 'bangus', name: 'Bangus (Milkfish)', unit: 'kg', quantity: 0.5 },
      { id: 'suka', name: 'Vinegar', unit: 'bottle', quantity: 0.15 },
      { id: 'bawang', name: 'Garlic', nameTagalog: 'Bawang', unit: 'kg', quantity: 0.02 },
      { id: 'ginger', name: 'Ginger', unit: 'kg', quantity: 0.02 },
      { id: 'sibuyas', name: 'Onion', nameTagalog: 'Sibuyas', unit: 'kg', quantity: 0.05 },
    ],
    recipe: '1. Arrange bangus slices in a single layer in a pot.\n2. Add vinegar, crushed garlic, sliced ginger, sliced onion, whole peppercorns, and a little water.\n3. Add salt to taste and a small amount of sugar to balance the sourness.\n4. Bring to a boil WITHOUT stirring (to keep the fish intact).\n5. Reduce heat and simmer for 15 minutes.\n6. Add long green chili and bitter gourd slices (optional).\n7. Serve warm over steamed rice.',
    calories: 290,
    tags: ['light', 'calming', 'high-protein'],
    prepMinutes: 25,
  },
  {
    id: 'nilaga',
    name: 'Nilaga',
    nameTagalog: 'Nilagang Baka',
    category: 'dinner',
    ingredients: [
      { id: 'pork-belly', name: 'Beef Shank (or Pork)', unit: 'kg', quantity: 0.5 },
      { id: 'sayote', name: 'Sayote', unit: 'kg', quantity: 0.2 },
      { id: 'sitaw', name: 'Sitaw (String Beans)', unit: 'kg', quantity: 0.1 },
      { id: 'kangkong', name: 'Kangkong', unit: 'kg', quantity: 0.15 },
      { id: 'sibuyas', name: 'Onion', nameTagalog: 'Sibuyas', unit: 'kg', quantity: 0.05 },
      { id: 'cabbage', name: 'Cabbage', unit: 'kg', quantity: 0.15 },
    ],
    recipe: '1. Boil beef in a large pot with whole peppercorns and onion for 45 minutes until tender.\n2. Skim off fat and scum from the surface.\n3. Add potato wedges and corn on the cob; cook for 10 minutes.\n4. Add sayote wedges and cabbage; cook for 5 minutes.\n5. Add kangkong and string beans; cook for 2 minutes.\n6. Season with patis and pepper.\n7. Serve as a hearty soup with rice on the side.',
    calories: 380,
    tags: ['savory', 'filling', 'calming'],
    prepMinutes: 55,
  },
  {
    id: 'ginataang-kalabasa',
    name: 'Ginataang Kalabasa',
    nameTagalog: 'Ginataang Kalabasa',
    category: 'dinner',
    ingredients: [
      { id: 'kalabasa', name: 'Kalabasa (Squash)', unit: 'kg', quantity: 0.4 },
      { id: 'coconut-milk', name: 'Coconut Milk', unit: 'pack', quantity: 2 },
      { id: 'pork-ground', name: 'Ground Pork', unit: 'kg', quantity: 0.15 },
      { id: 'sitaw', name: 'Sitaw (String Beans)', unit: 'kg', quantity: 0.15 },
      { id: 'bawang', name: 'Garlic', nameTagalog: 'Bawang', unit: 'kg', quantity: 0.02 },
      { id: 'sibuyas', name: 'Onion', nameTagalog: 'Sibuyas', unit: 'kg', quantity: 0.05 },
    ],
    recipe: '1. Sauté garlic and onion in a pot until fragrant.\n2. Add ground pork and cook until browned.\n3. Pour in coconut milk and bring to a gentle boil.\n4. Add cubed kalabasa (squash) and simmer for 10 minutes until soft.\n5. Add sitaw cut into 2-inch pieces; cook for 5 minutes.\n6. Season with patis and pepper. Stir gently to avoid mashing the squash.\n7. Serve over steamed rice.',
    calories: 350,
    tags: ['savory', 'calming', 'filling'],
    prepMinutes: 30,
  },

  // ─── SNACKS ───────────────────────────────────────────────────
  {
    id: 'turon',
    name: 'Turon',
    nameTagalog: 'Turon',
    category: 'snack',
    ingredients: [
      { id: 'cooking-oil', name: 'Cooking Oil', unit: 'L', quantity: 0.2 },
      { id: 'sugar', name: 'Brown Sugar', unit: 'kg', quantity: 0.05 },
    ],
    recipe: '1. Peel ripe saba bananas and slice each in half lengthwise.\n2. Roll each piece in brown sugar.\n3. Place a banana piece (and optionally a slice of jackfruit) on a lumpia wrapper and roll tightly, sealing the edge with water.\n4. Heat oil in a deep pan.\n5. Fry turon in batches until golden brown and the sugar caramelizes, about 3 minutes.\n6. Drain on paper towels. Serve warm.',
    calories: 180,
    tags: ['light', 'low-cost'],
    prepMinutes: 15,
  },
  {
    id: 'banana-cue',
    name: 'Banana Cue',
    nameTagalog: 'Banana Cue',
    category: 'snack',
    ingredients: [
      { id: 'cooking-oil', name: 'Cooking Oil', unit: 'L', quantity: 0.25 },
      { id: 'sugar', name: 'Brown Sugar', unit: 'kg', quantity: 0.08 },
    ],
    recipe: '1. Heat oil in a deep pan or wok.\n2. Peel saba bananas and leave them whole.\n3. Add bananas to the hot oil and fry for 2 minutes.\n4. Sprinkle brown sugar generously over the bananas in the oil.\n5. Continue frying, turning occasionally, until the sugar caramelizes into a dark amber coating, about 5 minutes.\n6. Remove with skewers or tongs and let cool slightly. Serve on bamboo sticks.',
    calories: 200,
    tags: ['light', 'low-cost'],
    prepMinutes: 10,
  },
  {
    id: 'tokwat-baboy',
    name: "Tokwa't Baboy",
    nameTagalog: "Tokwa't Baboy",
    category: 'lunch',
    ingredients: [
      { id: 'tofu', name: 'Tofu', unit: 'block', quantity: 1 },
      { id: 'pork-belly', name: 'Pork Belly', unit: 'kg', quantity: 0.25 },
      { id: 'toyo', name: 'Soy Sauce', unit: 'bottle', quantity: 0.1 },
      { id: 'suka', name: 'Vinegar', unit: 'bottle', quantity: 0.1 },
      { id: 'sibuyas', name: 'Onion', nameTagalog: 'Sibuyas', unit: 'kg', quantity: 0.05 },
      { id: 'cooking-oil', name: 'Cooking Oil', unit: 'L', quantity: 0.15 },
    ],
    recipe: '1. Boil pork belly in water with peppercorns and bay leaf until tender, about 30 minutes. Slice into bite-sized pieces.\n2. Cut tofu into cubes and deep-fry until golden and crispy. Drain.\n3. Make the sauce: combine soy sauce, vinegar, diced onion, minced chili, and a pinch of sugar.\n4. Arrange fried tofu and sliced pork on a plate.\n5. Pour the sauce over the top.\n6. Serve as a snack or appetizer (pulutan).',
    calories: 320,
    tags: ['savory', 'filling', 'high-protein'],
    prepMinutes: 40,
  },
];
